### PR TITLE
Fix Reset Odometry And Add Reset Drivetrain

### LINKED ISSUE #15: Clean up DriveTrain reset code
`resetGyro()` shouldn’t call `resetOdometry()` – Those are distinct functionalities. Also, all your reset code needs to be called in `autoInit()` or somewhere – It currently is not ever called.

### PR DESCRIPTION
**Pull request by Jacob4649**
Fix #15

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 1]
```diff
@@ -87,6 +87,9 @@ public DriveTrain() {
 
     m_odometry = new DifferentialDriveOdometry(Rotation2d.fromDegrees(-getGyroAngle()), new Pose2d(
         Constants.ROBOT_START_X, Constants.ROBOT_START_Y, Rotation2d.fromDegrees(Constants.ROBOT_START_ANGLE)));
+
+    resetDriveTrain();
+    //TODO : Call reset drivetrain at the beginning of anyg auto command once they get merged in
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: Why not just call this in `autonomousInit()`? That way we're sure it gets called at the start.

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 2]
```diff
@@ -171,9 +165,18 @@ public void resetEncoders() {
...
+  }
+
+  public void resetDriveTrain() {
+    resetDriveTrain(0.0, 0.0, 0.0);
+  }
+
+  public void resetDriveTrain(double xPos, double yPos, double angle) {
+    resetEncoders();
+    resetGyro();
+    resetOdometry(xPos, yPos, angle);
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: Seems a bit overkill to have all these private one-line functions - Why not just move the functionality into this function? It's also a bit dangerous, since it's still possible to reset one of them individually (Although only from within the subsystem)

**Review by matthew-reynolds — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 1 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: If I'm not mistaken, calling this in `autonomousInit` would require the `m_driveTrain` to be publicly accessible. I'm not sure if this is in line with the new WPILIB design philosophy. As long as you're ok with that, I can put it in.

Comment (matthew-reynolds) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: That's true, perhaps a corresponding function (eg `setupAuto()`) in RobotContainer would be better. We're going to need to pass subsystems to the autonomous command group anyways, so we'll need some mechanism to access the subsystems at enable time. Adding in this reset call seems like it could go alongside the command group setup.

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 2 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: Resolved in 39a8ae883c904573ca4ff47c598cede92706d725

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 1 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: Resolved in b26f458

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 3]
```diff
@@ -160,20 +142,24 @@ public double getAverageDistance() {
...
   }
 
-  /**
-   * resets the encoder
-   */
-  public void resetEncoders() {
-    m_leftEncoder.reset();
-    m_rightEncoder.reset();
+  public void resetDriveTrain() {
+    resetDriveTrain(0.0, 0.0, 0.0);
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java:148]: Please add a javadoc, like the one you have below for the corresponding `resetDriveTrain(double, double, double)` below.

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 1 above)
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: Please remove this `TODO`

File: src/main/java/frc/robot/RobotContainer.java [hunk 4]
```diff
@@ -124,4 +124,8 @@ private void configureButtonBindings() {
   public Command getAutonomousCommand() {
     return null;
   }
+
+  public void setupAuto() {
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/RobotContainer.java:142]: Please add an appropriate javadoc

File: src/main/java/frc/robot/Robot.java [hunk 5]
```diff
@@ -74,6 +74,9 @@ public void disabledPeriodic() {
    */
   @Override
   public void autonomousInit() {
+
+    m_robotContainer.setupAuto();
+
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/Robot.java]: Let's also move the autonomous command logic (line 80-85) into our `setupAuto()`, and remove `RobotContainer::getAutonomousCommand()`. Might as well keep all our autonomous code together.

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 6]
```diff
@@ -160,20 +142,24 @@ public double getAverageDistance() {
...
-  /**
-   * resets the gyro and the odometry
+   /**
+   * Resets the odometry and sets the robot to the inputted position.
+   * Also resets encoders and gyro
+   * 
+   * @param xPos  the x position of the robot in inches
+   * @param yPos  the y position of the robot in inches
+   * @param angle the angle of the robot in degrees (WPILIB Format, degrees
+   *              counterclockwise with 0 being straight ahead)
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: If you wish to shorten this, you can say "the angle of the robot in degrees CCW from forward"

**Review by matthew-reynolds — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 6 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: resolved in 0bf8ea1

File: src/main/java/frc/robot/Robot.java (hunk 5 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/Robot.java]: Resolved in 0bf8ea1

File: src/main/java/frc/robot/RobotContainer.java (hunk 4 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/RobotContainer.java:142]: Resolved in 0bf8ea1

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 1 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: Resolved in 0bf8ea1

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 3 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java:148]: Resolved in 0bf8ea1

Comment (matthew-reynolds) [reply src/main/java/frc/robot/subsystems/DriveTrain.java:148]: "To the inputted position" doesn't make sense here. Should say something about x=0, y=0, angle=0

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 7]
```diff
@@ -161,21 +142,28 @@ public double getAverageDistance() {
...
-    m_leftEncoder.reset();
-    m_rightEncoder.reset();
+  public void resetDriveTrain() {
+    resetDriveTrain(0.0, 0.0, 0.0);
   }
 
-  /**
-   * resets the gyro and the odometry
+   /**
+   * Resets the odometry and sets the robot to the inputted position.
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: `inputted`->`specified`

File: src/main/java/frc/robot/subsystems/DriveTrain.java [hunk 8]
```diff
@@ -161,21 +142,28 @@ public double getAverageDistance() {
...
-  public void resetGyro() {
+  public void resetDriveTrain(double xPos, double yPos, double angle) {
+    m_leftEncoder.reset();
+    m_rightEncoder.reset();
     m_gyro.reset();
-    resetOdometry();
+    m_odometry.resetPosition(new Pose2d(xPos, yPos, new Rotation2d(xPos, yPos)), Rotation2d.fromDegrees(angle));
   }
-
+
```
Comment (matthew-reynolds) [inline src/main/java/frc/robot/subsystems/DriveTrain.java]: Trailing whitespace

**Review by matthew-reynolds — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 8 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: resolved in 0929fdf

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 7 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java]: resolved in 0929fdf

File: src/main/java/frc/robot/subsystems/DriveTrain.java (hunk 3 above)
Comment (Jacob4649) [reply src/main/java/frc/robot/subsystems/DriveTrain.java:148]: resolved in 0929fdf

**Review by matthew-reynolds — APPROVED** [review]
